export enum DomainEventType {
  // Team Events
  TEAM_CREATED = 'TEAM_CREATED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  TEAM_DELETED = 'TEAM_DELETED',
  TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED = 'TEAM_MEMBER_REMOVED',

  // Project Events
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  PROJECT_MEMBER_ADDED = 'PROJECT_MEMBER_ADDED',
  PROJECT_MEMBER_REMOVED = 'PROJECT_MEMBER_REMOVED',

  // Task Events (Phase 3)
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_DELETED = 'TASK_DELETED',
  TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',
  SUBTASK_CREATED = 'SUBTASK_CREATED',
  SUBTASK_UPDATED = 'SUBTASK_UPDATED',
  SUBTASK_DELETED = 'SUBTASK_DELETED',

  // Attachment Events (Phase 7)
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  ATTACHMENT_DELETED = 'ATTACHMENT_DELETED'
}

export interface DomainEvent<T = any> {
  type: DomainEventType;
  actorId: number;
  payload: T;
  timestamp: string;
}

export type EventHandler<T = any> = (event: DomainEvent<T>) => Promise<void> | void;
